services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - proposal_saas_mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: proposal_saas

volumes:
  proposal_saas_mongo:
